import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "about",
    description: "Generated by create next app",
};

interface IPops {
    children: React.ReactNode;
}

export default function PublicLayout(props: IPops) {
    const { children } = props;
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}
