// 1

import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Provider } from "react-redux";
import store from "./redux/store";
import ProviderRedux from "@/layouts/ProviderRedux";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderRedux>
          {children}
          <Toaster position="top-center" />
        </ProviderRedux>
      </body>
    </html>
  );
}
