

import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/layouts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css'></link>
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
